services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Прокси API на хосте
    networks:
      - app-network
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017  # URI для подключения к MongoDB

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-vite/dist:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"  # Доступ к Nginx на хосте
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest  # Используем образ MongoDB
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Укажите имя пользователя
      MONGO_INITDB_ROOT_PASSWORD: password  # Укажите пароль
    ports:
      - "27017:27017"  # Проброс порта для доступа к MongoDB
    volumes:
      - mongo_data:/data/db  # Сохраняем данные в постоянном хранилище
    networks:
      - app-network  # Добавляем к сети

networks:
  app-network:  # Определяем сеть для всех сервисов

volumes:
  mongo_data:  # Определяем постоянное хранилище для MongoDB
